### ISSUE TITLE
Python 3.6 is currently not supported

### ISSUE THREAD

**Issue by arjan-s** [SecurityInnovation/PGPy#166]
Importing pgpy (version 0.4.0) from the Python console gives the following error:

```
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/project_py36/lib/python3.6/site-packages/pgpy/__init__.py", line 5, in <module>
    from .pgp import PGPKey
  File "/home/user/.virtualenvs/project_py36/lib/python3.6/site-packages/pgpy/pgp.py", line 23, in <module>
    from .constants import CompressionAlgorithm
  File "/home/user/.virtualenvs/project_py36/lib/python3.6/site-packages/pgpy/constants.py", line 22, in <module>
    from .types import FlagEnum
  File "/home/user/.virtualenvs/project_py36/lib/python3.6/site-packages/pgpy/types.py", line 641, in <module>
    class FlagEnum(six.with_metaclass(FlagEnumMeta, IntEnum)):
  File "/usr/lib64/python3.6/enum.py", line 119, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/usr/lib64/python3.6/enum.py", line 439, in _get_mixins_
    raise TypeError("new enumerations must be created as "
TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)`
>>> 
```

**Comment by Commod0re** [comment]
Yeah, I noticed that yesterday as well :(

It seems to be an issue with changes to EnumMeta between 3.5 and 3.6. It doesn't like `six.with_metaclass` nor `@six.add_metaclass`. I'm trying to find a workaround that doesn't break everything else
