### ISSUE TITLE
PGPKey.pubkey.subkeys don't have parent attribute.

### ISSUE THREAD

**Issue by J08nY** [SecurityInnovation/PGPy#194]
I encountered a strange bug:
```
======================================================================
ERROR: MockAndMonkeyLayer ConfigLayer PGPConfigLayer test_decrypt (mailman_pgp.runners.tests.test_incoming.TestIncoming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johny/gsoc/psf/mailman/mailman-pgp/src/mailman_pgp/runners/tests/test_incoming.py", line 112, in test_decrypt
    emsg = self.pgp_list.pubkey.encrypt(pmsg)
  File "/home/johny/gsoc/psf/mailman/PGPy/pgpy/decorators.py", line 125, in _action
    with self.usage(key, kwargs.get('user', None)) as _key:
  File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/johny/gsoc/psf/mailman/PGPy/pgpy/decorators.py", line 92, in usage
    if self.flags & set(_key._get_key_flags(user)):
  File "/home/johny/gsoc/psf/mailman/PGPy/pgpy/pgp.py", line 1708, in _get_key_flags
    return next(self.self_signatures).key_flags
  File "/home/johny/gsoc/psf/mailman/PGPy/pgpy/pgp.py", line 1359, in self_signatures
    else (self.parent.fingerprint.keyid, SignatureType.Subkey_Binding)
AttributeError: 'NoneType' object has no attribute 'fingerprint'
----------------------------------------------------------------------
```
With keys generated like this:  https://gitlab.com/J08nY/mailman-pgp/blob/master/src/mailman_pgp/pgp/keygen.py

This all comes down to the pubkeys subkeys not having a proper `parent` attribute. While the original private keys subkeys have the `parent` attribute pointing at the private key.

I think the problem is around [pgp.py#L1320](https://github.com/SecurityInnovation/PGPy/blob/master/pgpy/pgp.py#L1320) where the pubkeys subkeys are created and it's obvious they won't have any `parent` set because they have no way to know about the newly created parent.

```python
                # get the public half of each subkey
                for skid, subkey in self.subkeys.items():
                    pub.subkeys[skid] = subkey.pubkey
```

I think doing something like
```python
                # get the public half of each subkey
                for skid, subkey in self.subkeys.items():
                    pub.subkeys[skid] = subkey.pubkey
                    pub.subkeys[skid].parent = pub
```
where `pub` is the newly created public sibling.

**Comment by J08nY** [comment]
Fixed by ddaca9338a43f7565aa49efca2f30b09db45d968.
