### ISSUE TITLE
Try further ciphers from a pubkey's preference list if the first one is not supported

### ISSUE THREAD

**Issue by Wolf480pl** [SecurityInnovation/PGPy#243]
Currently, if I try to encrypt something to a pubkey whose symmetric algorithm preference list starts with a cipher unsupported by PGPy, eg. TwoFish, I get a `PGPEncryptionError: Cipher <cipher> not supported` exception (example stacktrace below).

PGPy should instead try the next cipher on the list, and only fail if none of the ciphers on the preference list are supported.

```
[2018-07-14 14:35:16 +0000] [1367] [ERROR] Error handling request /privacy/test-email
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/metasrht/common.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/metasrht/blueprints/privacy.py", line 58, in privacy_testemail_POST
    site_key=site_key_id)
  File "/usr/lib/python3.6/site-packages/metasrht/email.py", line 23, in send_email
    srht.email.send_email(body, *args, encrypt_key=encrypt_key)
  File "/usr/lib/python3.6/site-packages/srht/email.py", line 66, in send_email
    encrypted = str(pubkey.encrypt(pgp_msg))
  File "/usr/lib/python3.6/site-packages/pgpy/decorators.py", line 129, in _action
    return action(_key, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pgpy/pgp.py", line 2204, in encrypt
    skedata.encrypt(sessionkey, cipher_algo, message.__bytes__())
  File "/usr/lib/python3.6/site-packages/pgpy/packet/packets.py", line 1542, in encrypt
    self.ct = _encrypt(data, key, alg)
  File "/usr/lib/python3.6/site-packages/pgpy/symenc.py", line 28, in _encrypt
    raise PGPEncryptionError("Cipher {:s} not supported".format(alg.name))
pgpy.errors.PGPEncryptionError: Cipher Twofish256 not supported
```

**Comment by Amir-m-a** [comment]
here Stop Iteration will be raised if no preferred encryption algorithm is specified in public key, even if one is provided in prefs.
https://github.com/SecurityInnovation/PGPy/blob/02766befcd5ee6c3a5d3ec0c8b46aaea1f9bb30c/pgpy/pgp.py#L2440-L2441
it's better to use the algorithm in argument at least instead of an exception imo.

thnx for great library btw
