### ISSUE TITLE
pgpy installation fails because of cryptography module

### ISSUE THREAD

**Issue by sudobhat** [SecurityInnovation/PGPy#366]
Seems like dependency cryptography is broken.

PgPy ( 0.5.3 ) installation does not work anymore. ( pip3 install pgpy )

OS: Ubuntu 18.0.4
pip3 version 9.0.1

```Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6f0wo2u8/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```
Any workarounds?

**Comment by sudobhat** [comment]
Upgrading pip to the most recent version solved the issue:

python3 -m pip install -U pip
